name: Dispatching
on:
  workflow_dispatch:
    types: [build]

jobs:
  echo:
    name: Print Date
    runs-on: ubuntu-latest
    steps:
      - name: Date
        run: date
      - name: Access External Payload
        run: echo "${{ github.event.client_payload }}""