name: NodeJS Matrix
on: [push]
jobs:
  node-version:
    strategy:
      matrix:
        node-version: [8, 10, 12]
      fail-fast: true
      max-parallel: 2
    name: Print Node.js Version Before Install
    runs-on: ubuntu-latest
    steps:
      - name: Log Node version
        run: node -v
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Log Node Version ${{ matrix.node-version }} After Install
        run: node -v
